import { useEffect, useState } from "react";
import Navigation from "@/components/Navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Activity, Compass, MapPinned, Route } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type Point={name:string;value:number};
type Insights={summary:{movements:number;uniqueCows:number;firstDate:string;lastDate:string;averageDistanceKm:number};regions:Point[];categories:Point[];vendors:Point[];monthly:{month:string;movements:number}[]};

export default function Dashboard(){
 const [data,setData]=useState<Insights|null>(null);
 useEffect(()=>{fetch(`${import.meta.env.BASE_URL}movement-insights.json`).then(r=>r.json()).then(setData)},[]);
 return <div className="min-h-screen bg-[#f7f4f8]"><Navigation/><PageHeader/><main className="mx-auto max-w-[1500px] space-y-6 px-5 py-7 lg:px-8">
  {!data?<Card><CardContent className="py-10 text-slate-500">Loading movement intelligence…</CardContent></Card>:<>
   <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={<Activity/>} label="Historical movements" value={data.summary.movements.toLocaleString()} detail={`${data.summary.firstDate} to ${data.summary.lastDate}`}/><Kpi icon={<Route/>} label="Fleet coverage" value={data.summary.uniqueCows.toLocaleString()} detail="Unique COW assets"/><Kpi icon={<Compass/>} label="Average movement" value={`${data.summary.averageDistanceKm} km`} detail="Recorded distance"/><Kpi icon={<MapPinned/>} label="Regional coverage" value={data.regions.length.toString()} detail="Kingdom operating regions"/></div>
   <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><ChartCard title="Movement activity trend" subtitle="Monthly movements — most recent 24 months"><ResponsiveContainer width="100%" height={310}><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" stroke="#eee7f0"/><XAxis dataKey="month" tick={{fontSize:11}} interval={2}/><YAxis tick={{fontSize:11}}/><Tooltip/><Line type="monotone" dataKey="movements" stroke="#8c2ca8" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Movement by destination region" subtitle="Aggregate historical distribution"><ResponsiveContainer width="100%" height={310}><BarChart data={data.regions} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#eee7f0"/><XAxis type="number" tick={{fontSize:11}}/><YAxis type="category" dataKey="name" width={65} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="value" fill="#ff375e" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer></ChartCard></div>
   <div className="grid gap-6 xl:grid-cols-2"><ChartCard title="Movement purpose profile" subtitle="Top historical movement categories"><ResponsiveContainer width="100%" height={330}><BarChart data={data.categories}><CartesianGrid strokeDasharray="3 3" stroke="#eee7f0"/><XAxis dataKey="name" tick={{fontSize:10}} angle={-20} textAnchor="end" height={80}/><YAxis tick={{fontSize:11}}/><Tooltip/><Bar dataKey="value" fill="#8c2ca8" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Technology vendor footprint" subtitle="Normalized vendor distribution"><div className="space-y-5 pt-3">{data.vendors.map(v=><div key={v.name}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-[#25102f]">{v.name}</span><span className="text-slate-500">{v.value.toLocaleString()} records</span></div><div className="h-3 overflow-hidden rounded-full bg-[#eee7f0]"><div className="h-full rounded-full bg-gradient-to-r from-[#8c2ca8] to-[#ff375e]" style={{width:`${v.value/Math.max(...data.vendors.map(x=>x.value))*100}%`}}/></div></div>)}</div></ChartCard></div>
  </>}
 </main></div>
}
function PageHeader(){return <header className="border-b border-[#e6dce9] bg-white"><div className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8c2ca8]">Movement Intelligence</p><h1 className="mt-2 text-3xl font-bold text-[#25102f]">Historical movement analytics</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Sanitized operational patterns across the national COW fleet. No record-level or location-identifying data is displayed.</p></div></header>}
function Kpi({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <Card className="border-[#e6dce9] shadow-sm"><CardContent className="flex items-start justify-between pt-6"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-[#25102f]">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div><span className="rounded-xl bg-[#8c2ca8]/10 p-3 text-[#8c2ca8]">{icon}</span></CardContent></Card>}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <Card className="border-[#e6dce9] shadow-sm"><CardHeader><CardTitle className="text-lg text-[#25102f]">{title}</CardTitle><p className="text-xs text-slate-500">{subtitle}</p></CardHeader><CardContent>{children}</CardContent></Card>}
