import Navigation from "@/components/Navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Archive, CheckCircle2, CloudCog, Database, FileCheck2, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";

const controls=[
 {icon:LockKeyhole,title:"Access control",text:"All analytical routes require an authenticated session. Production authentication will be connected to the approved identity provider."},
 {icon:Database,title:"Data minimization",text:"The public demonstration excludes raw history, coordinates, routes, and the full forecast set. Only five approved upcoming expectations are shown."},
 {icon:FileCheck2,title:"Validation",text:"Input data is normalized, date-checked, deduplicated, and validated before model training."},
 {icon:Archive,title:"Retention",text:"Training snapshots and model artifacts will follow the approved STC retention and audit policy."},
];

export default function DataManagement(){return <div className="min-h-screen bg-[#f7f4f8]"><Navigation/><header className="border-b border-[#e6dce9] bg-white"><div className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8c2ca8]">Data Governance</p><h1 className="mt-2 text-3xl font-bold text-[#25102f]">Controlled data and model lifecycle</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">A clear separation between this sanitized demonstration and the future protected operational data environment.</p></div></header><main className="mx-auto max-w-[1500px] space-y-6 px-5 py-7 lg:px-8">
<section className="grid gap-5 md:grid-cols-2">{controls.map(({icon:Icon,title,text})=><Card key={title} className="border-[#e6dce9] shadow-sm"><CardContent className="flex gap-5 pt-6"><span className="h-fit rounded-xl bg-[#8c2ca8]/10 p-3 text-[#8c2ca8]"><Icon/></span><div><h2 className="text-lg font-bold text-[#25102f]">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div></CardContent></Card>)}</section>
<Card className="border-[#e6dce9] shadow-sm"><CardHeader><CardTitle className="text-xl text-[#25102f]">Target production architecture</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-5"><Stage icon={<CloudCog/>} title="Approved source" text="CMDB / controlled tracker"/><Stage icon={<ShieldCheck/>} title="Secure ingestion" text="Validation and access policy"/><Stage icon={<RefreshCw/>} title="Model pipeline" text="Versioned retraining"/><Stage icon={<Database/>} title="Private storage" text="Row-level security"/><Stage icon={<CheckCircle2/>} title="Decision layer" text="Authorized dashboards"/></div></CardContent></Card>
<Card className="border-emerald-200 bg-emerald-50/70"><CardContent className="flex gap-4 pt-6"><ShieldCheck className="h-6 w-6 shrink-0 text-emerald-700"/><div><p className="font-bold text-emerald-900">Public repository sanitized</p><p className="mt-1 text-sm leading-6 text-emerald-900/70">The deployed repository retains aggregate counts and model validation metrics only. Operational movement history and detailed prediction results are not published.</p></div></CardContent></Card>
</main></div>}
function Stage({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-[#eee7f0] bg-[#faf8fb] p-4"><span className="text-[#8c2ca8]">{icon}</span><p className="mt-4 text-sm font-bold text-[#25102f]">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>}
