import Navigation from "@/components/Navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BrainCircuit, CheckCircle2, Clock3, Layers3, MapPinned, ShieldAlert, Target } from "lucide-react";

const models=[
 {icon:MapPinned,name:"Next Region Classifier",purpose:"Ranks the most probable destination regions for each future COW movement.",primary:"80.4%",primaryLabel:"Top-1 accuracy",secondary:"95.2%",secondaryLabel:"Top-3 accuracy",status:"Production candidate"},
 {icon:Layers3,name:"Location Category Classifier",purpose:"Predicts the likely operational purpose: warehouse, event, royal, or other category.",primary:"49.1%",primaryLabel:"Top-1 accuracy",secondary:"90.6%",secondaryLabel:"Top-3 accuracy",status:"Decision support"},
 {icon:Clock3,name:"Movement Timing Regressor",purpose:"Estimates days until the next movement using asset history and operational context.",primary:"128 days",primaryLabel:"Mean absolute error",secondary:"0.023",secondaryLabel:"R² score",status:"Experimental"},
];

export default function MovementPredictions(){return <div className="min-h-screen bg-[#f7f4f8]"><Navigation/><header className="border-b border-[#e6dce9] bg-white"><div className="mx-auto max-w-[1500px] px-5 py-7 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#8c2ca8]">Predictive Models</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold text-[#25102f]"><BrainCircuit className="h-8 w-8 text-[#8c2ca8]"/>Validated movement forecasting</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">Transparent model performance based on chronological validation. Individual asset predictions remain in the protected operational data layer.</p></div><Badge className="w-fit bg-emerald-600 px-3 py-1">Model v2.0</Badge></div></div></header>
<main className="mx-auto max-w-[1500px] space-y-6 px-5 py-7 lg:px-8">
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Target/>} label="Training sequences" value="1,554"/><Metric icon={<CheckCircle2/>} label="Validation sequences" value="693"/><Metric icon={<MapPinned/>} label="Historical movements" value="2,694"/><Metric icon={<Clock3/>} label="Training period" value="2021–2026"/></div>
 <div className="grid gap-5 lg:grid-cols-3">{models.map(({icon:Icon,...m})=><Card key={m.name} className="border-[#e6dce9] shadow-sm"><CardHeader><div className="mb-5 flex items-start justify-between"><span className="rounded-xl bg-[#8c2ca8]/10 p-3 text-[#8c2ca8]"><Icon/></span><Badge variant="outline" className={m.status==="Experimental"?"border-amber-300 text-amber-700":"border-emerald-300 text-emerald-700"}>{m.status}</Badge></div><CardTitle className="text-xl text-[#25102f]">{m.name}</CardTitle><p className="pt-2 text-sm leading-6 text-slate-500">{m.purpose}</p></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><ModelMetric value={m.primary} label={m.primaryLabel}/><ModelMetric value={m.secondary} label={m.secondaryLabel}/></div></CardContent></Card>)}</div>
 <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><Card className="border-[#e6dce9] shadow-sm"><CardHeader><CardTitle className="text-xl text-[#25102f]">Validation methodology</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-slate-600"><Step n="01" title="Chronological split" text="Models train on movements before 1 January 2025 and validate against later movement outcomes."/><Step n="02" title="Leakage prevention" text="Future movement fields are excluded from the feature set available at prediction time."/><Step n="03" title="Operational interpretation" text="Top-3 probabilities support planners; timing estimates are clearly marked experimental."/></CardContent></Card><Card className="border-amber-200 bg-amber-50/70 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg text-amber-900"><ShieldAlert className="h-5 w-5"/>Responsible use</CardTitle></CardHeader><CardContent className="text-sm leading-6 text-amber-900/70">Predictions support—not replace—operational judgment. Planners should combine model outputs with event schedules, site readiness, access restrictions, fleet condition, and STC approval requirements.</CardContent></Card></div>
</main></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <Card className="border-[#e6dce9] shadow-sm"><CardContent className="flex items-center gap-4 pt-6"><span className="rounded-xl bg-[#8c2ca8]/10 p-3 text-[#8c2ca8]">{icon}</span><div><p className="text-xs uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-2xl font-bold text-[#25102f]">{value}</p></div></CardContent></Card>}
function ModelMetric({value,label}:{value:string;label:string}){return <div className="rounded-xl bg-[#f7f4f8] p-4"><p className="text-2xl font-bold text-[#8c2ca8]">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className="flex gap-4 rounded-xl border border-[#eee7f0] p-4"><span className="font-bold text-[#ff375e]">{n}</span><div><p className="font-semibold text-[#25102f]">{title}</p><p className="mt-1 leading-6">{text}</p></div></div>}
