import { ParsedCOWAsset, ParsedMovement } from "./dataParser";

export const SAMPLE_COW_ASSETS: ParsedCOWAsset[] = [
  {
    cowid: "COW001",
    site_label: "Riyadh Central",
    region: "Riyadh",
    district: "Central",
    city: "Riyadh",
    location: "Business District",
    latitude: 24.7136,
    longitude: 46.6753,
    last_deploying_date: "2024-01-15",
    vendor: "Ericsson",
    shelter_outdoor: "Outdoor",
    remarks: "Active, excellent signal",
  },
  {
    cowid: "COW002",
    site_label: "Jeddah North",
    region: "Jeddah",
    district: "North",
    city: "Jeddah",
    location: "Red Sea District",
    latitude: 21.5921,
    longitude: 39.1721,
    last_deploying_date: "2024-01-10",
    vendor: "Nokia",
    shelter_outdoor: "Shelter",
    remarks: "Under maintenance",
  },
  {
    cowid: "COW003",
    site_label: "Dammam East",
    region: "Dammam",
    district: "East",
    city: "Dammam",
    location: "Eastern Province Hub",
    latitude: 26.3954,
    longitude: 50.1957,
    last_deploying_date: "2024-01-20",
    vendor: "Huawei",
    shelter_outdoor: "Outdoor",
    remarks: "Ready for deployment",
  },
  {
    cowid: "COW004",
    site_label: "Riyadh South",
    region: "Riyadh",
    district: "South",
    city: "Riyadh",
    location: "Airport Area",
    latitude: 24.6282,
    longitude: 46.7104,
    last_deploying_date: "2024-01-18",
    vendor: "Ericsson",
    shelter_outdoor: "Shelter",
    remarks: "Active deployment",
  },
  {
    cowid: "COW005",
    site_label: "Mecca Al Haram",
    region: "Mecca",
    district: "Central",
    city: "Mecca",
    location: "Holy Mosque Area",
    latitude: 21.4225,
    longitude: 39.8262,
    last_deploying_date: "2024-01-12",
    vendor: "Nokia",
    shelter_outdoor: "Outdoor",
    remarks: "Recent event deployment",
  },
];

export const SAMPLE_MOVEMENTS: ParsedMovement[] = [
  {
    movement_id: "MVT_10001",
    cowid: "COW001",
    site_label: "Riyadh Central",
    region: "Riyadh",
    district: "Central",
    city: "Riyadh",
    latitude: 24.7136,
    longitude: 46.6753,
    vendor: "Ericsson",
    tech_used: "5G",
    tower_height: 30,
    vsat: true,
    warehouse_id: "ACES_RYD",
    deploy_start_date: "2023-12-01",
    deploy_end_date: "2023-12-10",
    success_flag: 1,
    issue_type: "None",
    remarks: "Smooth deployment, high uptime",
  },
  {
    movement_id: "MVT_10002",
    cowid: "COW001",
    site_label: "Riyadh Central",
    region: "Riyadh",
    district: "Central",
    city: "Riyadh",
    latitude: 24.7136,
    longitude: 46.6753,
    vendor: "Ericsson",
    tech_used: "5G",
    tower_height: 30,
    vsat: true,
    warehouse_id: "ACES_RYD",
    deploy_start_date: "2024-01-05",
    deploy_end_date: "2024-01-15",
    success_flag: 1,
    issue_type: "None",
    remarks: "Excellent performance",
  },
  {
    movement_id: "MVT_10003",
    cowid: "COW002",
    site_label: "Jeddah North",
    region: "Jeddah",
    district: "North",
    city: "Jeddah",
    latitude: 21.5921,
    longitude: 39.1721,
    vendor: "Nokia",
    tech_used: "4G/5G",
    tower_height: 25,
    vsat: false,
    warehouse_id: "ACES_JED",
    deploy_start_date: "2023-11-15",
    deploy_end_date: "2023-11-28",
    success_flag: 1,
    issue_type: "None",
    remarks: "Reliable performance",
  },
  {
    movement_id: "MVT_10004",
    cowid: "COW002",
    site_label: "Jeddah North",
    region: "Jeddah",
    district: "North",
    city: "Jeddah",
    latitude: 21.5921,
    longitude: 39.1721,
    vendor: "Nokia",
    tech_used: "4G/5G",
    tower_height: 25,
    vsat: false,
    warehouse_id: "ACES_JED",
    deploy_start_date: "2024-01-10",
    deploy_end_date: "2024-01-20",
    success_flag: 0,
    issue_type: "Hardware_Failure",
    remarks: "Minor hardware issues, resolved",
  },
  {
    movement_id: "MVT_10005",
    cowid: "COW003",
    site_label: "Dammam East",
    region: "Dammam",
    district: "East",
    city: "Dammam",
    latitude: 26.3954,
    longitude: 50.1957,
    vendor: "Huawei",
    tech_used: "4G",
    tower_height: 28,
    vsat: true,
    warehouse_id: "ACES_DMM",
    deploy_start_date: "2023-10-01",
    deploy_end_date: "2023-10-20",
    success_flag: 1,
    issue_type: "None",
    remarks: "Successful deployment",
  },
  {
    movement_id: "MVT_10006",
    cowid: "COW003",
    site_label: "Dammam East",
    region: "Dammam",
    district: "East",
    city: "Dammam",
    latitude: 26.3954,
    longitude: 50.1957,
    vendor: "Huawei",
    tech_used: "4G",
    tower_height: 28,
    vsat: true,
    warehouse_id: "ACES_DMM",
    deploy_start_date: "2024-01-20",
    deploy_end_date: "2024-01-30",
    success_flag: 1,
    issue_type: "None",
    remarks: "Ready for next event",
  },
  {
    movement_id: "MVT_10007",
    cowid: "COW004",
    site_label: "Riyadh South",
    region: "Riyadh",
    district: "South",
    city: "Riyadh",
    latitude: 24.6282,
    longitude: 46.7104,
    vendor: "Ericsson",
    tech_used: "5G",
    tower_height: 32,
    vsat: true,
    warehouse_id: "ACES_RYD",
    deploy_start_date: "2023-12-20",
    deploy_end_date: "2024-01-10",
    success_flag: 1,
    issue_type: "None",
    remarks: "Perfect uptime record",
  },
  {
    movement_id: "MVT_10008",
    cowid: "COW005",
    site_label: "Mecca Al Haram",
    region: "Mecca",
    district: "Central",
    city: "Mecca",
    latitude: 21.4225,
    longitude: 39.8262,
    vendor: "Nokia",
    tech_used: "5G",
    tower_height: 35,
    vsat: true,
    warehouse_id: "ACES_MKH",
    deploy_start_date: "2024-01-01",
    deploy_end_date: "2024-01-12",
    success_flag: 1,
    issue_type: "None",
    remarks: "High-demand event deployment",
  },
];
